name: CI Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Usar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Build backend
        run: npm run build

      - name: Generar ZIP de actualización
        run: npm run build:update

      - name: Obtener versión
        id: pkg
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Subir update
        run: |
          curl -X POST ${{ secrets.UPLOAD_URL }} \
          -H "Authorization: Bearer ${{ secrets.CI_TOKEN }}" \
          -F "file=@update.zip" \
          -F "version=$VERSION" \
          -F "app=easysales" \
          -F "idApp=1" \
          -F "tipo=backend"

